using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.UI;

namespace CMART5
{
    public partial class GUI_RequestInfo : Form
    {
        public GUI_RequestInfo()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            lookUpEdit1.Properties.DataSource = new CMART5.Cmart5DataContext().SANPHAMs;
            lookUpEdit1.Properties.DisplayMember = "TENSP";
            lookUpEdit1.Properties.ValueMember = "idSANPHAM";
        }
        public string IDtick;


        Cmart5DataContext dbl;
        int index;

        private void loadData()
        {
            dbl = new Cmart5DataContext();
            var ds = dbl.CTPHIEUDEXUATs.Where(st => st.idPHIEUDEXUAT.Contains(this.IDtick)).ToList();
            gcRequestInfo.DataSource = ds;
            lookUpEdit1.Properties.ValueMember = "idSANPHAM";
            lookUpEdit1.ItemIndex = 0;
            numb.ResetText();
            btnSave.Enabled = false;
        }

        private void GUI_HQTicketInfo_Load(object sender, EventArgs e)
        {
            loadData();

        }

        private void btnAdd_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            string idpro = lookUpEdit1.EditValue.ToString();
            int qt = int.Parse(numb.Value.ToString());
            if (idpro == null )
            {
                MessageBox.Show("Vui lòng chọn sản phẩm");
            }
            else if(qt == 0)
            {
                MessageBox.Show("Vui lòng chọn số lượng sản phẩm");
            }
            else
            {
                BUS.BUS_Tickets buz = new BUS.BUS_Tickets();
                buz.AddRQicketInfo(this.IDtick, idpro, qt);
                loadData();
            }

        }

        private void gvRequestInfo_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            index = e.FocusedRowHandle;

        }
        private void gvRequestInfo_DoubleClick(object sender, EventArgs e)
        {
            lookUpEdit1.EditValue = gvRequestInfo.GetRowCellValue(index, this.IDSP);
            lookUpEdit1.Enabled = false;
            btnAdd.Enabled = false;
            numb.Value = (int)gvRequestInfo.GetRowCellValue(index, this.SL);
        }


        private void btnSave_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            string idp = lookUpEdit1.EditValue.ToString();
            int qa = int.Parse(numb.Value.ToString());
            if (idp == null )
            {
                MessageBox.Show("Vui lòng chọn sản phẩm");
            }
            else if (qa == 0)
            {
                MessageBox.Show("Vui lòng chọn số lượng sản phẩm");
            }
            else
            {
                BUS.BUS_Tickets buzu = new BUS.BUS_Tickets();
                buzu.UpdateRQTicketInfo(IDtick, idp, qa);
                loadData();
                btnAdd.Enabled = true;
                lookUpEdit1.Enabled = true;
            }
        }

        private void btnprint_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Report.RQTick report = new Report.RQTick();
            report.DataSource = dbl.CTPHIEUDEXUATs.ToList();
            report.ShowPreviewDialog();
        }

        private void btnEdit2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            btnSave.Enabled = true;
            btnAdd.Enabled = false;
            //string idHQT = gvRequestInfo.GetRowCellValue(index, this.IDHQ).ToString();
            lookUpEdit1.EditValue = gvRequestInfo.GetRowCellValue(index, this.IDSP);
            lookUpEdit1.Enabled = false;
            btnAdd.Enabled = false;
            numb.Value = (int)gvRequestInfo.GetRowCellValue(index, this.SL);
        }
    }
}
