#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMART5
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CMART5")]
	public partial class Cmart5DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTHOADON(CTHOADON instance);
    partial void UpdateCTHOADON(CTHOADON instance);
    partial void DeleteCTHOADON(CTHOADON instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertCTPHIEUDEXUAT(CTPHIEUDEXUAT instance);
    partial void UpdateCTPHIEUDEXUAT(CTPHIEUDEXUAT instance);
    partial void DeleteCTPHIEUDEXUAT(CTPHIEUDEXUAT instance);
    partial void InsertCTPHIEUNHAPHANGCHINHANH(CTPHIEUNHAPHANGCHINHANH instance);
    partial void UpdateCTPHIEUNHAPHANGCHINHANH(CTPHIEUNHAPHANGCHINHANH instance);
    partial void DeleteCTPHIEUNHAPHANGCHINHANH(CTPHIEUNHAPHANGCHINHANH instance);
    partial void InsertCTPHIEUNHAPHANGTRUSO(CTPHIEUNHAPHANGTRUSO instance);
    partial void UpdateCTPHIEUNHAPHANGTRUSO(CTPHIEUNHAPHANGTRUSO instance);
    partial void DeleteCTPHIEUNHAPHANGTRUSO(CTPHIEUNHAPHANGTRUSO instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHUYENMAI(KHUYENMAI instance);
    partial void UpdateKHUYENMAI(KHUYENMAI instance);
    partial void DeleteKHUYENMAI(KHUYENMAI instance);
    partial void InsertLICHSUGIA(LICHSUGIA instance);
    partial void UpdateLICHSUGIA(LICHSUGIA instance);
    partial void DeleteLICHSUGIA(LICHSUGIA instance);
    partial void InsertLOAISANPHAM(LOAISANPHAM instance);
    partial void UpdateLOAISANPHAM(LOAISANPHAM instance);
    partial void DeleteLOAISANPHAM(LOAISANPHAM instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertPHIEUDEXUAT(PHIEUDEXUAT instance);
    partial void UpdatePHIEUDEXUAT(PHIEUDEXUAT instance);
    partial void DeletePHIEUDEXUAT(PHIEUDEXUAT instance);
    partial void InsertPHIEUNHAPHANGCHINHANH(PHIEUNHAPHANGCHINHANH instance);
    partial void UpdatePHIEUNHAPHANGCHINHANH(PHIEUNHAPHANGCHINHANH instance);
    partial void DeletePHIEUNHAPHANGCHINHANH(PHIEUNHAPHANGCHINHANH instance);
    partial void InsertPHIEUNHAPHANGTRUSO(PHIEUNHAPHANGTRUSO instance);
    partial void UpdatePHIEUNHAPHANGTRUSO(PHIEUNHAPHANGTRUSO instance);
    partial void DeletePHIEUNHAPHANGTRUSO(PHIEUNHAPHANGTRUSO instance);
    partial void InsertSANPHAM(SANPHAM instance);
    partial void UpdateSANPHAM(SANPHAM instance);
    partial void DeleteSANPHAM(SANPHAM instance);
    #endregion
		
		public Cmart5DataContext() : 
				base(global::CMART5.Properties.Settings.Default.CMART5ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Cmart5DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cmart5DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cmart5DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cmart5DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTHOADON> CTHOADONs
		{
			get
			{
				return this.GetTable<CTHOADON>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUDEXUAT> CTPHIEUDEXUATs
		{
			get
			{
				return this.GetTable<CTPHIEUDEXUAT>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUNHAPHANGCHINHANH> CTPHIEUNHAPHANGCHINHANHs
		{
			get
			{
				return this.GetTable<CTPHIEUNHAPHANGCHINHANH>();
			}
		}
		
		public System.Data.Linq.Table<CTPHIEUNHAPHANGTRUSO> CTPHIEUNHAPHANGTRUSOs
		{
			get
			{
				return this.GetTable<CTPHIEUNHAPHANGTRUSO>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHUYENMAI> KHUYENMAIs
		{
			get
			{
				return this.GetTable<KHUYENMAI>();
			}
		}
		
		public System.Data.Linq.Table<LICHSUGIA> LICHSUGIAs
		{
			get
			{
				return this.GetTable<LICHSUGIA>();
			}
		}
		
		public System.Data.Linq.Table<LOAISANPHAM> LOAISANPHAMs
		{
			get
			{
				return this.GetTable<LOAISANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDEXUAT> PHIEUDEXUATs
		{
			get
			{
				return this.GetTable<PHIEUDEXUAT>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPHANGCHINHANH> PHIEUNHAPHANGCHINHANHs
		{
			get
			{
				return this.GetTable<PHIEUNHAPHANGCHINHANH>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUNHAPHANGTRUSO> PHIEUNHAPHANGTRUSOs
		{
			get
			{
				return this.GetTable<PHIEUNHAPHANGTRUSO>();
			}
		}
		
		public System.Data.Linq.Table<SANPHAM> SANPHAMs
		{
			get
			{
				return this.GetTable<SANPHAM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHOADON")]
	public partial class CTHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idHOADON;
		
		private string _idSANPHAM;
		
		private System.Nullable<double> _DONGIA;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHOADONChanging(string value);
    partial void OnidHOADONChanged();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnDONGIAChanging(System.Nullable<double> value);
    partial void OnDONGIAChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CTHOADON()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHOADON", DbType="NVarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idHOADON
		{
			get
			{
				return this._idHOADON;
			}
			set
			{
				if ((this._idHOADON != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidHOADONChanging(value);
					this.SendPropertyChanging();
					this._idHOADON = value;
					this.SendPropertyChanged("idHOADON");
					this.OnidHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float")]
		public System.Nullable<double> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHOADON", Storage="_HOADON", ThisKey="idHOADON", OtherKey="idHOADON", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CTHOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CTHOADONs.Add(this);
						this._idHOADON = value.idHOADON;
					}
					else
					{
						this._idHOADON = default(string);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTHOADON", Storage="_SANPHAM", ThisKey="idSANPHAM", OtherKey="idSANPHAM", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CTHOADONs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CTHOADONs.Add(this);
						this._idSANPHAM = value.idSANPHAM;
					}
					else
					{
						this._idSANPHAM = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idTAIKHOAN;
		
		private string _HOTEN;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private string _CMND;
		
		private string _TENDANGNHAP;
		
		private string _MATKHAU;
		
		private int _QUYEN;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<PHIEUDEXUAT> _PHIEUDEXUATs;
		
		private EntitySet<PHIEUNHAPHANGCHINHANH> _PHIEUNHAPHANGCHINHANHs;
		
		private EntitySet<PHIEUNHAPHANGTRUSO> _PHIEUNHAPHANGTRUSOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTAIKHOANChanging(string value);
    partial void OnidTAIKHOANChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnTENDANGNHAPChanging(string value);
    partial void OnTENDANGNHAPChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnQUYENChanging(int value);
    partial void OnQUYENChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._PHIEUDEXUATs = new EntitySet<PHIEUDEXUAT>(new Action<PHIEUDEXUAT>(this.attach_PHIEUDEXUATs), new Action<PHIEUDEXUAT>(this.detach_PHIEUDEXUATs));
			this._PHIEUNHAPHANGCHINHANHs = new EntitySet<PHIEUNHAPHANGCHINHANH>(new Action<PHIEUNHAPHANGCHINHANH>(this.attach_PHIEUNHAPHANGCHINHANHs), new Action<PHIEUNHAPHANGCHINHANH>(this.detach_PHIEUNHAPHANGCHINHANHs));
			this._PHIEUNHAPHANGTRUSOs = new EntitySet<PHIEUNHAPHANGTRUSO>(new Action<PHIEUNHAPHANGTRUSO>(this.attach_PHIEUNHAPHANGTRUSOs), new Action<PHIEUNHAPHANGTRUSO>(this.detach_PHIEUNHAPHANGTRUSOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTAIKHOAN", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idTAIKHOAN
		{
			get
			{
				return this._idTAIKHOAN;
			}
			set
			{
				if ((this._idTAIKHOAN != value))
				{
					this.OnidTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._idTAIKHOAN = value;
					this.SendPropertyChanged("idTAIKHOAN");
					this.OnidTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDANGNHAP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TENDANGNHAP
		{
			get
			{
				return this._TENDANGNHAP;
			}
			set
			{
				if ((this._TENDANGNHAP != value))
				{
					this.OnTENDANGNHAPChanging(value);
					this.SendPropertyChanging();
					this._TENDANGNHAP = value;
					this.SendPropertyChanged("TENDANGNHAP");
					this.OnTENDANGNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="Int NOT NULL")]
		public int QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_HOADON", Storage="_HOADONs", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_PHIEUDEXUAT", Storage="_PHIEUDEXUATs", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN")]
		public EntitySet<PHIEUDEXUAT> PHIEUDEXUATs
		{
			get
			{
				return this._PHIEUDEXUATs;
			}
			set
			{
				this._PHIEUDEXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_PHIEUNHAPHANGCHINHANH", Storage="_PHIEUNHAPHANGCHINHANHs", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN")]
		public EntitySet<PHIEUNHAPHANGCHINHANH> PHIEUNHAPHANGCHINHANHs
		{
			get
			{
				return this._PHIEUNHAPHANGCHINHANHs;
			}
			set
			{
				this._PHIEUNHAPHANGCHINHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_PHIEUNHAPHANGTRUSO", Storage="_PHIEUNHAPHANGTRUSOs", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN")]
		public EntitySet<PHIEUNHAPHANGTRUSO> PHIEUNHAPHANGTRUSOs
		{
			get
			{
				return this._PHIEUNHAPHANGTRUSOs;
			}
			set
			{
				this._PHIEUNHAPHANGTRUSOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach_PHIEUDEXUATs(PHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_PHIEUDEXUATs(PHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach_PHIEUNHAPHANGCHINHANHs(PHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_PHIEUNHAPHANGCHINHANHs(PHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
		
		private void attach_PHIEUNHAPHANGTRUSOs(PHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_PHIEUNHAPHANGTRUSOs(PHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUDEXUAT")]
	public partial class CTPHIEUDEXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPHIEUDEXUAT;
		
		private string _idSANPHAM;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<PHIEUDEXUAT> _PHIEUDEXUAT;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPHIEUDEXUATChanging(string value);
    partial void OnidPHIEUDEXUATChanged();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CTPHIEUDEXUAT()
		{
			this._PHIEUDEXUAT = default(EntityRef<PHIEUDEXUAT>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUDEXUAT", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPHIEUDEXUAT
		{
			get
			{
				return this._idPHIEUDEXUAT;
			}
			set
			{
				if ((this._idPHIEUDEXUAT != value))
				{
					if (this._PHIEUDEXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPHIEUDEXUATChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUDEXUAT = value;
					this.SendPropertyChanged("idPHIEUDEXUAT");
					this.OnidPHIEUDEXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDEXUAT_CTPHIEUDEXUAT", Storage="_PHIEUDEXUAT", ThisKey="idPHIEUDEXUAT", OtherKey="idPHIEUDEXUAT", IsForeignKey=true)]
		public PHIEUDEXUAT PHIEUDEXUAT
		{
			get
			{
				return this._PHIEUDEXUAT.Entity;
			}
			set
			{
				PHIEUDEXUAT previousValue = this._PHIEUDEXUAT.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDEXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDEXUAT.Entity = null;
						previousValue.CTPHIEUDEXUATs.Remove(this);
					}
					this._PHIEUDEXUAT.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUDEXUATs.Add(this);
						this._idPHIEUDEXUAT = value.idPHIEUDEXUAT;
					}
					else
					{
						this._idPHIEUDEXUAT = default(string);
					}
					this.SendPropertyChanged("PHIEUDEXUAT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTPHIEUDEXUAT", Storage="_SANPHAM", ThisKey="idSANPHAM", OtherKey="idSANPHAM", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CTPHIEUDEXUATs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUDEXUATs.Add(this);
						this._idSANPHAM = value.idSANPHAM;
					}
					else
					{
						this._idSANPHAM = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUNHAPHANGCHINHANH")]
	public partial class CTPHIEUNHAPHANGCHINHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPHIEUCHINHANH;
		
		private string _idSANPHAM;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _TINHTRANG;
		
		private EntityRef<PHIEUNHAPHANGCHINHANH> _PHIEUNHAPHANGCHINHANH;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPHIEUCHINHANHChanging(string value);
    partial void OnidPHIEUCHINHANHChanged();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public CTPHIEUNHAPHANGCHINHANH()
		{
			this._PHIEUNHAPHANGCHINHANH = default(EntityRef<PHIEUNHAPHANGCHINHANH>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUCHINHANH", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPHIEUCHINHANH
		{
			get
			{
				return this._idPHIEUCHINHANH;
			}
			set
			{
				if ((this._idPHIEUCHINHANH != value))
				{
					if (this._PHIEUNHAPHANGCHINHANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPHIEUCHINHANHChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUCHINHANH = value;
					this.SendPropertyChanged("idPHIEUCHINHANH");
					this.OnidPHIEUCHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(40)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPHANGCHINHANH_CTPHIEUNHAPHANGCHINHANH", Storage="_PHIEUNHAPHANGCHINHANH", ThisKey="idPHIEUCHINHANH", OtherKey="idPHIEUCHINHANH", IsForeignKey=true)]
		public PHIEUNHAPHANGCHINHANH PHIEUNHAPHANGCHINHANH
		{
			get
			{
				return this._PHIEUNHAPHANGCHINHANH.Entity;
			}
			set
			{
				PHIEUNHAPHANGCHINHANH previousValue = this._PHIEUNHAPHANGCHINHANH.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAPHANGCHINHANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAPHANGCHINHANH.Entity = null;
						previousValue.CTPHIEUNHAPHANGCHINHANHs.Remove(this);
					}
					this._PHIEUNHAPHANGCHINHANH.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUNHAPHANGCHINHANHs.Add(this);
						this._idPHIEUCHINHANH = value.idPHIEUCHINHANH;
					}
					else
					{
						this._idPHIEUCHINHANH = default(string);
					}
					this.SendPropertyChanged("PHIEUNHAPHANGCHINHANH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTPHIEUNHAPHANGCHINHANH", Storage="_SANPHAM", ThisKey="idSANPHAM", OtherKey="idSANPHAM", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CTPHIEUNHAPHANGCHINHANHs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUNHAPHANGCHINHANHs.Add(this);
						this._idSANPHAM = value.idSANPHAM;
					}
					else
					{
						this._idSANPHAM = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPHIEUNHAPHANGTRUSO")]
	public partial class CTPHIEUNHAPHANGTRUSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPHIEUTRUSO;
		
		private string _idSANPHAM;
		
		private int _SOLUONG;
		
		private double _GIANHAP;
		
		private System.DateTime _HANSD;
		
		private string _TINHTRANG;
		
		private EntityRef<PHIEUNHAPHANGTRUSO> _PHIEUNHAPHANGTRUSO;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPHIEUTRUSOChanging(string value);
    partial void OnidPHIEUTRUSOChanged();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnSOLUONGChanging(int value);
    partial void OnSOLUONGChanged();
    partial void OnGIANHAPChanging(double value);
    partial void OnGIANHAPChanged();
    partial void OnHANSDChanging(System.DateTime value);
    partial void OnHANSDChanged();
    partial void OnTINHTRANGChanging(string value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public CTPHIEUNHAPHANGTRUSO()
		{
			this._PHIEUNHAPHANGTRUSO = default(EntityRef<PHIEUNHAPHANGTRUSO>);
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUTRUSO", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPHIEUTRUSO
		{
			get
			{
				return this._idPHIEUTRUSO;
			}
			set
			{
				if ((this._idPHIEUTRUSO != value))
				{
					if (this._PHIEUNHAPHANGTRUSO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPHIEUTRUSOChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUTRUSO = value;
					this.SendPropertyChanged("idPHIEUTRUSO");
					this.OnidPHIEUTRUSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int NOT NULL")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIANHAP", DbType="Float NOT NULL")]
		public double GIANHAP
		{
			get
			{
				return this._GIANHAP;
			}
			set
			{
				if ((this._GIANHAP != value))
				{
					this.OnGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._GIANHAP = value;
					this.SendPropertyChanged("GIANHAP");
					this.OnGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANSD", DbType="DateTime NOT NULL")]
		public System.DateTime HANSD
		{
			get
			{
				return this._HANSD;
			}
			set
			{
				if ((this._HANSD != value))
				{
					this.OnHANSDChanging(value);
					this.SendPropertyChanging();
					this._HANSD = value;
					this.SendPropertyChanged("HANSD");
					this.OnHANSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="NVarChar(40)")]
		public string TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPHANGTRUSO_CTPHIEUNHAPHANGTRUSO", Storage="_PHIEUNHAPHANGTRUSO", ThisKey="idPHIEUTRUSO", OtherKey="idPHIEUTRUSO", IsForeignKey=true)]
		public PHIEUNHAPHANGTRUSO PHIEUNHAPHANGTRUSO
		{
			get
			{
				return this._PHIEUNHAPHANGTRUSO.Entity;
			}
			set
			{
				PHIEUNHAPHANGTRUSO previousValue = this._PHIEUNHAPHANGTRUSO.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAPHANGTRUSO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAPHANGTRUSO.Entity = null;
						previousValue.CTPHIEUNHAPHANGTRUSOs.Remove(this);
					}
					this._PHIEUNHAPHANGTRUSO.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUNHAPHANGTRUSOs.Add(this);
						this._idPHIEUTRUSO = value.idPHIEUTRUSO;
					}
					else
					{
						this._idPHIEUTRUSO = default(string);
					}
					this.SendPropertyChanged("PHIEUNHAPHANGTRUSO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTPHIEUNHAPHANGTRUSO", Storage="_SANPHAM", ThisKey="idSANPHAM", OtherKey="idSANPHAM", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CTPHIEUNHAPHANGTRUSOs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CTPHIEUNHAPHANGTRUSOs.Add(this);
						this._idSANPHAM = value.idSANPHAM;
					}
					else
					{
						this._idSANPHAM = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idHOADON;
		
		private System.Nullable<System.DateTime> _NGAYBAN;
		
		private double _TONGTIEN;
		
		private double _TIENKHACHDUA;
		
		private double _TIENTRALAI;
		
		private int _TONGSOLUONG;
		
		private int _SOPOS;
		
		private string _idTAIKHOAN;
		
		private EntitySet<CTHOADON> _CTHOADONs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidHOADONChanging(string value);
    partial void OnidHOADONChanged();
    partial void OnNGAYBANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBANChanged();
    partial void OnTONGTIENChanging(double value);
    partial void OnTONGTIENChanged();
    partial void OnTIENKHACHDUAChanging(double value);
    partial void OnTIENKHACHDUAChanged();
    partial void OnTIENTRALAIChanging(double value);
    partial void OnTIENTRALAIChanged();
    partial void OnTONGSOLUONGChanging(int value);
    partial void OnTONGSOLUONGChanged();
    partial void OnSOPOSChanging(int value);
    partial void OnSOPOSChanged();
    partial void OnidTAIKHOANChanging(string value);
    partial void OnidTAIKHOANChanged();
    #endregion
		
		public HOADON()
		{
			this._CTHOADONs = new EntitySet<CTHOADON>(new Action<CTHOADON>(this.attach_CTHOADONs), new Action<CTHOADON>(this.detach_CTHOADONs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idHOADON", DbType="NVarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idHOADON
		{
			get
			{
				return this._idHOADON;
			}
			set
			{
				if ((this._idHOADON != value))
				{
					this.OnidHOADONChanging(value);
					this.SendPropertyChanging();
					this._idHOADON = value;
					this.SendPropertyChanged("idHOADON");
					this.OnidHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBAN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYBAN
		{
			get
			{
				return this._NGAYBAN;
			}
			set
			{
				if ((this._NGAYBAN != value))
				{
					this.OnNGAYBANChanging(value);
					this.SendPropertyChanging();
					this._NGAYBAN = value;
					this.SendPropertyChanged("NGAYBAN");
					this.OnNGAYBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float NOT NULL")]
		public double TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENKHACHDUA", DbType="Float NOT NULL")]
		public double TIENKHACHDUA
		{
			get
			{
				return this._TIENKHACHDUA;
			}
			set
			{
				if ((this._TIENKHACHDUA != value))
				{
					this.OnTIENKHACHDUAChanging(value);
					this.SendPropertyChanging();
					this._TIENKHACHDUA = value;
					this.SendPropertyChanged("TIENKHACHDUA");
					this.OnTIENKHACHDUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENTRALAI", DbType="Float NOT NULL")]
		public double TIENTRALAI
		{
			get
			{
				return this._TIENTRALAI;
			}
			set
			{
				if ((this._TIENTRALAI != value))
				{
					this.OnTIENTRALAIChanging(value);
					this.SendPropertyChanging();
					this._TIENTRALAI = value;
					this.SendPropertyChanged("TIENTRALAI");
					this.OnTIENTRALAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGSOLUONG", DbType="Int NOT NULL")]
		public int TONGSOLUONG
		{
			get
			{
				return this._TONGSOLUONG;
			}
			set
			{
				if ((this._TONGSOLUONG != value))
				{
					this.OnTONGSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._TONGSOLUONG = value;
					this.SendPropertyChanged("TONGSOLUONG");
					this.OnTONGSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPOS", DbType="Int NOT NULL")]
		public int SOPOS
		{
			get
			{
				return this._SOPOS;
			}
			set
			{
				if ((this._SOPOS != value))
				{
					this.OnSOPOSChanging(value);
					this.SendPropertyChanging();
					this._SOPOS = value;
					this.SendPropertyChanged("SOPOS");
					this.OnSOPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTAIKHOAN", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string idTAIKHOAN
		{
			get
			{
				return this._idTAIKHOAN;
			}
			set
			{
				if ((this._idTAIKHOAN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._idTAIKHOAN = value;
					this.SendPropertyChanged("idTAIKHOAN");
					this.OnidTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHOADON", Storage="_CTHOADONs", ThisKey="idHOADON", OtherKey="idHOADON")]
		public EntitySet<CTHOADON> CTHOADONs
		{
			get
			{
				return this._CTHOADONs;
			}
			set
			{
				this._CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_HOADON", Storage="_TAIKHOAN", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._idTAIKHOAN = value.idTAIKHOAN;
					}
					else
					{
						this._idTAIKHOAN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHUYENMAI")]
	public partial class KHUYENMAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idKHUYENMAI;
		
		private string _idSANPHAM;
		
		private System.Nullable<double> _GIA_KM;
		
		private System.Nullable<System.DateTime> _TG_BATDAU;
		
		private System.Nullable<System.DateTime> _TG_KETTHUC;
		
		private string _NOIDUNG;
		
		private string _HINHANH;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKHUYENMAIChanging(string value);
    partial void OnidKHUYENMAIChanged();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnGIA_KMChanging(System.Nullable<double> value);
    partial void OnGIA_KMChanged();
    partial void OnTG_BATDAUChanging(System.Nullable<System.DateTime> value);
    partial void OnTG_BATDAUChanged();
    partial void OnTG_KETTHUCChanging(System.Nullable<System.DateTime> value);
    partial void OnTG_KETTHUCChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    #endregion
		
		public KHUYENMAI()
		{
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKHUYENMAI", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idKHUYENMAI
		{
			get
			{
				return this._idKHUYENMAI;
			}
			set
			{
				if ((this._idKHUYENMAI != value))
				{
					this.OnidKHUYENMAIChanging(value);
					this.SendPropertyChanging();
					this._idKHUYENMAI = value;
					this.SendPropertyChanged("idKHUYENMAI");
					this.OnidKHUYENMAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_KM", DbType="Float")]
		public System.Nullable<double> GIA_KM
		{
			get
			{
				return this._GIA_KM;
			}
			set
			{
				if ((this._GIA_KM != value))
				{
					this.OnGIA_KMChanging(value);
					this.SendPropertyChanging();
					this._GIA_KM = value;
					this.SendPropertyChanged("GIA_KM");
					this.OnGIA_KMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TG_BATDAU", DbType="DateTime")]
		public System.Nullable<System.DateTime> TG_BATDAU
		{
			get
			{
				return this._TG_BATDAU;
			}
			set
			{
				if ((this._TG_BATDAU != value))
				{
					this.OnTG_BATDAUChanging(value);
					this.SendPropertyChanging();
					this._TG_BATDAU = value;
					this.SendPropertyChanged("TG_BATDAU");
					this.OnTG_BATDAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TG_KETTHUC", DbType="DateTime")]
		public System.Nullable<System.DateTime> TG_KETTHUC
		{
			get
			{
				return this._TG_KETTHUC;
			}
			set
			{
				if ((this._TG_KETTHUC != value))
				{
					this.OnTG_KETTHUCChanging(value);
					this.SendPropertyChanging();
					this._TG_KETTHUC = value;
					this.SendPropertyChanged("TG_KETTHUC");
					this.OnTG_KETTHUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(100)")]
		public string NOIDUNG
		{
			get
			{
				return this._NOIDUNG;
			}
			set
			{
				if ((this._NOIDUNG != value))
				{
					this.OnNOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._NOIDUNG = value;
					this.SendPropertyChanged("NOIDUNG");
					this.OnNOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(100)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_KHUYENMAI", Storage="_SANPHAM", ThisKey="idSANPHAM", OtherKey="idSANPHAM", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.KHUYENMAIs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.KHUYENMAIs.Add(this);
						this._idSANPHAM = value.idSANPHAM;
					}
					else
					{
						this._idSANPHAM = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LICHSUGIA")]
	public partial class LICHSUGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSANPHAM;
		
		private double _GIABAN;
		
		private System.DateTime _NGAYHIEULUC;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnGIABANChanging(double value);
    partial void OnGIABANChanged();
    partial void OnNGAYHIEULUCChanging(System.DateTime value);
    partial void OnNGAYHIEULUCChanged();
    #endregion
		
		public LICHSUGIA()
		{
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHIEULUC", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NGAYHIEULUC
		{
			get
			{
				return this._NGAYHIEULUC;
			}
			set
			{
				if ((this._NGAYHIEULUC != value))
				{
					this.OnNGAYHIEULUCChanging(value);
					this.SendPropertyChanging();
					this._NGAYHIEULUC = value;
					this.SendPropertyChanged("NGAYHIEULUC");
					this.OnNGAYHIEULUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_LICHSUGIA", Storage="_SANPHAM", ThisKey="idSANPHAM", OtherKey="idSANPHAM", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.LICHSUGIAs.Remove(this);
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.LICHSUGIAs.Add(this);
						this._idSANPHAM = value.idSANPHAM;
					}
					else
					{
						this._idSANPHAM = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAISANPHAM")]
	public partial class LOAISANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idLOAISANPHAM;
		
		private string _TENLOAI;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidLOAISANPHAMChanging(string value);
    partial void OnidLOAISANPHAMChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public LOAISANPHAM()
		{
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLOAISANPHAM", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idLOAISANPHAM
		{
			get
			{
				return this._idLOAISANPHAM;
			}
			set
			{
				if ((this._idLOAISANPHAM != value))
				{
					this.OnidLOAISANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idLOAISANPHAM = value;
					this.SendPropertyChanged("idLOAISANPHAM");
					this.OnidLOAISANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(100)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAISANPHAM_SANPHAM", Storage="_SANPHAMs", ThisKey="idLOAISANPHAM", OtherKey="idLOAISANPHAM")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAISANPHAM = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAISANPHAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idNHACUNGCAP;
		
		private string _TENNHACUNGCAP;
		
		private string _DIACHINHACUNGCAP;
		
		private string _SDT;
		
		private EntitySet<PHIEUDEXUAT> _PHIEUDEXUATs;
		
		private EntitySet<SANPHAM> _SANPHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNHACUNGCAPChanging(string value);
    partial void OnidNHACUNGCAPChanged();
    partial void OnTENNHACUNGCAPChanging(string value);
    partial void OnTENNHACUNGCAPChanged();
    partial void OnDIACHINHACUNGCAPChanging(string value);
    partial void OnDIACHINHACUNGCAPChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._PHIEUDEXUATs = new EntitySet<PHIEUDEXUAT>(new Action<PHIEUDEXUAT>(this.attach_PHIEUDEXUATs), new Action<PHIEUDEXUAT>(this.detach_PHIEUDEXUATs));
			this._SANPHAMs = new EntitySet<SANPHAM>(new Action<SANPHAM>(this.attach_SANPHAMs), new Action<SANPHAM>(this.detach_SANPHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNHACUNGCAP", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idNHACUNGCAP
		{
			get
			{
				return this._idNHACUNGCAP;
			}
			set
			{
				if ((this._idNHACUNGCAP != value))
				{
					this.OnidNHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._idNHACUNGCAP = value;
					this.SendPropertyChanged("idNHACUNGCAP");
					this.OnidNHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHACUNGCAP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENNHACUNGCAP
		{
			get
			{
				return this._TENNHACUNGCAP;
			}
			set
			{
				if ((this._TENNHACUNGCAP != value))
				{
					this.OnTENNHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._TENNHACUNGCAP = value;
					this.SendPropertyChanged("TENNHACUNGCAP");
					this.OnTENNHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHINHACUNGCAP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DIACHINHACUNGCAP
		{
			get
			{
				return this._DIACHINHACUNGCAP;
			}
			set
			{
				if ((this._DIACHINHACUNGCAP != value))
				{
					this.OnDIACHINHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._DIACHINHACUNGCAP = value;
					this.SendPropertyChanged("DIACHINHACUNGCAP");
					this.OnDIACHINHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUDEXUAT", Storage="_PHIEUDEXUATs", ThisKey="idNHACUNGCAP", OtherKey="idNHACUNGCAP")]
		public EntitySet<PHIEUDEXUAT> PHIEUDEXUATs
		{
			get
			{
				return this._PHIEUDEXUATs;
			}
			set
			{
				this._PHIEUDEXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_SANPHAM", Storage="_SANPHAMs", ThisKey="idNHACUNGCAP", OtherKey="idNHACUNGCAP")]
		public EntitySet<SANPHAM> SANPHAMs
		{
			get
			{
				return this._SANPHAMs;
			}
			set
			{
				this._SANPHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDEXUATs(PHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_PHIEUDEXUATs(PHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
		
		private void attach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_SANPHAMs(SANPHAM entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDEXUAT")]
	public partial class PHIEUDEXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPHIEUDEXUAT;
		
		private System.DateTime _NGAYDEXUAT;
		
		private string _idNHACUNGCAP;
		
		private string _idTAIKHOAN;
		
		private EntitySet<CTPHIEUDEXUAT> _CTPHIEUDEXUATs;
		
		private EntitySet<PHIEUNHAPHANGTRUSO> _PHIEUNHAPHANGTRUSOs;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPHIEUDEXUATChanging(string value);
    partial void OnidPHIEUDEXUATChanged();
    partial void OnNGAYDEXUATChanging(System.DateTime value);
    partial void OnNGAYDEXUATChanged();
    partial void OnidNHACUNGCAPChanging(string value);
    partial void OnidNHACUNGCAPChanged();
    partial void OnidTAIKHOANChanging(string value);
    partial void OnidTAIKHOANChanged();
    #endregion
		
		public PHIEUDEXUAT()
		{
			this._CTPHIEUDEXUATs = new EntitySet<CTPHIEUDEXUAT>(new Action<CTPHIEUDEXUAT>(this.attach_CTPHIEUDEXUATs), new Action<CTPHIEUDEXUAT>(this.detach_CTPHIEUDEXUATs));
			this._PHIEUNHAPHANGTRUSOs = new EntitySet<PHIEUNHAPHANGTRUSO>(new Action<PHIEUNHAPHANGTRUSO>(this.attach_PHIEUNHAPHANGTRUSOs), new Action<PHIEUNHAPHANGTRUSO>(this.detach_PHIEUNHAPHANGTRUSOs));
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUDEXUAT", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPHIEUDEXUAT
		{
			get
			{
				return this._idPHIEUDEXUAT;
			}
			set
			{
				if ((this._idPHIEUDEXUAT != value))
				{
					this.OnidPHIEUDEXUATChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUDEXUAT = value;
					this.SendPropertyChanged("idPHIEUDEXUAT");
					this.OnidPHIEUDEXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDEXUAT", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYDEXUAT
		{
			get
			{
				return this._NGAYDEXUAT;
			}
			set
			{
				if ((this._NGAYDEXUAT != value))
				{
					this.OnNGAYDEXUATChanging(value);
					this.SendPropertyChanging();
					this._NGAYDEXUAT = value;
					this.SendPropertyChanged("NGAYDEXUAT");
					this.OnNGAYDEXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNHACUNGCAP", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string idNHACUNGCAP
		{
			get
			{
				return this._idNHACUNGCAP;
			}
			set
			{
				if ((this._idNHACUNGCAP != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._idNHACUNGCAP = value;
					this.SendPropertyChanged("idNHACUNGCAP");
					this.OnidNHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTAIKHOAN", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string idTAIKHOAN
		{
			get
			{
				return this._idTAIKHOAN;
			}
			set
			{
				if ((this._idTAIKHOAN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._idTAIKHOAN = value;
					this.SendPropertyChanged("idTAIKHOAN");
					this.OnidTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDEXUAT_CTPHIEUDEXUAT", Storage="_CTPHIEUDEXUATs", ThisKey="idPHIEUDEXUAT", OtherKey="idPHIEUDEXUAT")]
		public EntitySet<CTPHIEUDEXUAT> CTPHIEUDEXUATs
		{
			get
			{
				return this._CTPHIEUDEXUATs;
			}
			set
			{
				this._CTPHIEUDEXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDEXUAT_PHIEUNHAPHANGTRUSO", Storage="_PHIEUNHAPHANGTRUSOs", ThisKey="idPHIEUDEXUAT", OtherKey="idPHIEUDEXUAT")]
		public EntitySet<PHIEUNHAPHANGTRUSO> PHIEUNHAPHANGTRUSOs
		{
			get
			{
				return this._PHIEUNHAPHANGTRUSOs;
			}
			set
			{
				this._PHIEUNHAPHANGTRUSOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_PHIEUDEXUAT", Storage="_NHACUNGCAP", ThisKey="idNHACUNGCAP", OtherKey="idNHACUNGCAP", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.PHIEUDEXUATs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.PHIEUDEXUATs.Add(this);
						this._idNHACUNGCAP = value.idNHACUNGCAP;
					}
					else
					{
						this._idNHACUNGCAP = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_PHIEUDEXUAT", Storage="_TAIKHOAN", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.PHIEUDEXUATs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUDEXUATs.Add(this);
						this._idTAIKHOAN = value.idTAIKHOAN;
					}
					else
					{
						this._idTAIKHOAN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUDEXUATs(CTPHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDEXUAT = this;
		}
		
		private void detach_CTPHIEUDEXUATs(CTPHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDEXUAT = null;
		}
		
		private void attach_PHIEUNHAPHANGTRUSOs(PHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDEXUAT = this;
		}
		
		private void detach_PHIEUNHAPHANGTRUSOs(PHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDEXUAT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPHANGCHINHANH")]
	public partial class PHIEUNHAPHANGCHINHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPHIEUCHINHANH;
		
		private string _idPHIEUTRUSO;
		
		private System.DateTime _NGAYNHAP;
		
		private int _idCHINHANH;
		
		private string _idTAIKHOAN;
		
		private EntitySet<CTPHIEUNHAPHANGCHINHANH> _CTPHIEUNHAPHANGCHINHANHs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
		private EntityRef<PHIEUNHAPHANGTRUSO> _PHIEUNHAPHANGTRUSO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPHIEUCHINHANHChanging(string value);
    partial void OnidPHIEUCHINHANHChanged();
    partial void OnidPHIEUTRUSOChanging(string value);
    partial void OnidPHIEUTRUSOChanged();
    partial void OnNGAYNHAPChanging(System.DateTime value);
    partial void OnNGAYNHAPChanged();
    partial void OnidCHINHANHChanging(int value);
    partial void OnidCHINHANHChanged();
    partial void OnidTAIKHOANChanging(string value);
    partial void OnidTAIKHOANChanged();
    #endregion
		
		public PHIEUNHAPHANGCHINHANH()
		{
			this._CTPHIEUNHAPHANGCHINHANHs = new EntitySet<CTPHIEUNHAPHANGCHINHANH>(new Action<CTPHIEUNHAPHANGCHINHANH>(this.attach_CTPHIEUNHAPHANGCHINHANHs), new Action<CTPHIEUNHAPHANGCHINHANH>(this.detach_CTPHIEUNHAPHANGCHINHANHs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			this._PHIEUNHAPHANGTRUSO = default(EntityRef<PHIEUNHAPHANGTRUSO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUCHINHANH", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPHIEUCHINHANH
		{
			get
			{
				return this._idPHIEUCHINHANH;
			}
			set
			{
				if ((this._idPHIEUCHINHANH != value))
				{
					this.OnidPHIEUCHINHANHChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUCHINHANH = value;
					this.SendPropertyChanged("idPHIEUCHINHANH");
					this.OnidPHIEUCHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUTRUSO", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string idPHIEUTRUSO
		{
			get
			{
				return this._idPHIEUTRUSO;
			}
			set
			{
				if ((this._idPHIEUTRUSO != value))
				{
					if (this._PHIEUNHAPHANGTRUSO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPHIEUTRUSOChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUTRUSO = value;
					this.SendPropertyChanged("idPHIEUTRUSO");
					this.OnidPHIEUTRUSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCHINHANH", DbType="Int NOT NULL")]
		public int idCHINHANH
		{
			get
			{
				return this._idCHINHANH;
			}
			set
			{
				if ((this._idCHINHANH != value))
				{
					this.OnidCHINHANHChanging(value);
					this.SendPropertyChanging();
					this._idCHINHANH = value;
					this.SendPropertyChanged("idCHINHANH");
					this.OnidCHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTAIKHOAN", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string idTAIKHOAN
		{
			get
			{
				return this._idTAIKHOAN;
			}
			set
			{
				if ((this._idTAIKHOAN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._idTAIKHOAN = value;
					this.SendPropertyChanged("idTAIKHOAN");
					this.OnidTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPHANGCHINHANH_CTPHIEUNHAPHANGCHINHANH", Storage="_CTPHIEUNHAPHANGCHINHANHs", ThisKey="idPHIEUCHINHANH", OtherKey="idPHIEUCHINHANH")]
		public EntitySet<CTPHIEUNHAPHANGCHINHANH> CTPHIEUNHAPHANGCHINHANHs
		{
			get
			{
				return this._CTPHIEUNHAPHANGCHINHANHs;
			}
			set
			{
				this._CTPHIEUNHAPHANGCHINHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_PHIEUNHAPHANGCHINHANH", Storage="_TAIKHOAN", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.PHIEUNHAPHANGCHINHANHs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPHANGCHINHANHs.Add(this);
						this._idTAIKHOAN = value.idTAIKHOAN;
					}
					else
					{
						this._idTAIKHOAN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPHANGTRUSO_PHIEUNHAPHANGCHINHANH", Storage="_PHIEUNHAPHANGTRUSO", ThisKey="idPHIEUTRUSO", OtherKey="idPHIEUTRUSO", IsForeignKey=true)]
		public PHIEUNHAPHANGTRUSO PHIEUNHAPHANGTRUSO
		{
			get
			{
				return this._PHIEUNHAPHANGTRUSO.Entity;
			}
			set
			{
				PHIEUNHAPHANGTRUSO previousValue = this._PHIEUNHAPHANGTRUSO.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUNHAPHANGTRUSO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUNHAPHANGTRUSO.Entity = null;
						previousValue.PHIEUNHAPHANGCHINHANHs.Remove(this);
					}
					this._PHIEUNHAPHANGTRUSO.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPHANGCHINHANHs.Add(this);
						this._idPHIEUTRUSO = value.idPHIEUTRUSO;
					}
					else
					{
						this._idPHIEUTRUSO = default(string);
					}
					this.SendPropertyChanged("PHIEUNHAPHANGTRUSO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUNHAPHANGCHINHANHs(CTPHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPHANGCHINHANH = this;
		}
		
		private void detach_CTPHIEUNHAPHANGCHINHANHs(CTPHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPHANGCHINHANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUNHAPHANGTRUSO")]
	public partial class PHIEUNHAPHANGTRUSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idPHIEUTRUSO;
		
		private string _idPHIEUDEXUAT;
		
		private System.DateTime _NGAYNHAP;
		
		private double _TONGTIEN;
		
		private string _idTAIKHOAN;
		
		private EntitySet<CTPHIEUNHAPHANGTRUSO> _CTPHIEUNHAPHANGTRUSOs;
		
		private EntitySet<PHIEUNHAPHANGCHINHANH> _PHIEUNHAPHANGCHINHANHs;
		
		private EntityRef<PHIEUDEXUAT> _PHIEUDEXUAT;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPHIEUTRUSOChanging(string value);
    partial void OnidPHIEUTRUSOChanged();
    partial void OnidPHIEUDEXUATChanging(string value);
    partial void OnidPHIEUDEXUATChanged();
    partial void OnNGAYNHAPChanging(System.DateTime value);
    partial void OnNGAYNHAPChanged();
    partial void OnSOLUONGChanging(double value);
    partial void OnSOLUONGChanged();
    partial void OnidTAIKHOANChanging(string value);
    partial void OnidTAIKHOANChanged();
    #endregion
		
		public PHIEUNHAPHANGTRUSO()
		{
			this._CTPHIEUNHAPHANGTRUSOs = new EntitySet<CTPHIEUNHAPHANGTRUSO>(new Action<CTPHIEUNHAPHANGTRUSO>(this.attach_CTPHIEUNHAPHANGTRUSOs), new Action<CTPHIEUNHAPHANGTRUSO>(this.detach_CTPHIEUNHAPHANGTRUSOs));
			this._PHIEUNHAPHANGCHINHANHs = new EntitySet<PHIEUNHAPHANGCHINHANH>(new Action<PHIEUNHAPHANGCHINHANH>(this.attach_PHIEUNHAPHANGCHINHANHs), new Action<PHIEUNHAPHANGCHINHANH>(this.detach_PHIEUNHAPHANGCHINHANHs));
			this._PHIEUDEXUAT = default(EntityRef<PHIEUDEXUAT>);
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUTRUSO", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idPHIEUTRUSO
		{
			get
			{
				return this._idPHIEUTRUSO;
			}
			set
			{
				if ((this._idPHIEUTRUSO != value))
				{
					this.OnidPHIEUTRUSOChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUTRUSO = value;
					this.SendPropertyChanged("idPHIEUTRUSO");
					this.OnidPHIEUTRUSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPHIEUDEXUAT", DbType="NVarChar(8)")]
		public string idPHIEUDEXUAT
		{
			get
			{
				return this._idPHIEUDEXUAT;
			}
			set
			{
				if ((this._idPHIEUDEXUAT != value))
				{
					if (this._PHIEUDEXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPHIEUDEXUATChanging(value);
					this.SendPropertyChanging();
					this._idPHIEUDEXUAT = value;
					this.SendPropertyChanged("idPHIEUDEXUAT");
					this.OnidPHIEUDEXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="DateTime NOT NULL")]
		public System.DateTime NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float NOT NULL")]
		public double SOLUONG
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTAIKHOAN", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string idTAIKHOAN
		{
			get
			{
				return this._idTAIKHOAN;
			}
			set
			{
				if ((this._idTAIKHOAN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._idTAIKHOAN = value;
					this.SendPropertyChanged("idTAIKHOAN");
					this.OnidTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPHANGTRUSO_CTPHIEUNHAPHANGTRUSO", Storage="_CTPHIEUNHAPHANGTRUSOs", ThisKey="idPHIEUTRUSO", OtherKey="idPHIEUTRUSO")]
		public EntitySet<CTPHIEUNHAPHANGTRUSO> CTPHIEUNHAPHANGTRUSOs
		{
			get
			{
				return this._CTPHIEUNHAPHANGTRUSOs;
			}
			set
			{
				this._CTPHIEUNHAPHANGTRUSOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUNHAPHANGTRUSO_PHIEUNHAPHANGCHINHANH", Storage="_PHIEUNHAPHANGCHINHANHs", ThisKey="idPHIEUTRUSO", OtherKey="idPHIEUTRUSO")]
		public EntitySet<PHIEUNHAPHANGCHINHANH> PHIEUNHAPHANGCHINHANHs
		{
			get
			{
				return this._PHIEUNHAPHANGCHINHANHs;
			}
			set
			{
				this._PHIEUNHAPHANGCHINHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDEXUAT_PHIEUNHAPHANGTRUSO", Storage="_PHIEUDEXUAT", ThisKey="idPHIEUDEXUAT", OtherKey="idPHIEUDEXUAT", IsForeignKey=true)]
		public PHIEUDEXUAT PHIEUDEXUAT
		{
			get
			{
				return this._PHIEUDEXUAT.Entity;
			}
			set
			{
				PHIEUDEXUAT previousValue = this._PHIEUDEXUAT.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDEXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDEXUAT.Entity = null;
						previousValue.PHIEUNHAPHANGTRUSOs.Remove(this);
					}
					this._PHIEUDEXUAT.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPHANGTRUSOs.Add(this);
						this._idPHIEUDEXUAT = value.idPHIEUDEXUAT;
					}
					else
					{
						this._idPHIEUDEXUAT = default(string);
					}
					this.SendPropertyChanged("PHIEUDEXUAT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_PHIEUNHAPHANGTRUSO", Storage="_TAIKHOAN", ThisKey="idTAIKHOAN", OtherKey="idTAIKHOAN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.PHIEUNHAPHANGTRUSOs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.PHIEUNHAPHANGTRUSOs.Add(this);
						this._idTAIKHOAN = value.idTAIKHOAN;
					}
					else
					{
						this._idTAIKHOAN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPHIEUNHAPHANGTRUSOs(CTPHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPHANGTRUSO = this;
		}
		
		private void detach_CTPHIEUNHAPHANGTRUSOs(CTPHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPHANGTRUSO = null;
		}
		
		private void attach_PHIEUNHAPHANGCHINHANHs(PHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPHANGTRUSO = this;
		}
		
		private void detach_PHIEUNHAPHANGCHINHANHs(PHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUNHAPHANGTRUSO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANPHAM")]
	public partial class SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idSANPHAM;
		
		private string _TENSP;
		
		private string _HINHANH;
		
		private string _idLOAISANPHAM;
		
		private string _idNHACUNGCAP;
		
		private EntitySet<CTHOADON> _CTHOADONs;
		
		private EntitySet<CTPHIEUDEXUAT> _CTPHIEUDEXUATs;
		
		private EntitySet<CTPHIEUNHAPHANGCHINHANH> _CTPHIEUNHAPHANGCHINHANHs;
		
		private EntitySet<CTPHIEUNHAPHANGTRUSO> _CTPHIEUNHAPHANGTRUSOs;
		
		private EntitySet<KHUYENMAI> _KHUYENMAIs;
		
		private EntitySet<LICHSUGIA> _LICHSUGIAs;
		
		private EntityRef<LOAISANPHAM> _LOAISANPHAM;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidSANPHAMChanging(string value);
    partial void OnidSANPHAMChanged();
    partial void OnTENSPChanging(string value);
    partial void OnTENSPChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnidLOAISANPHAMChanging(string value);
    partial void OnidLOAISANPHAMChanged();
    partial void OnidNHACUNGCAPChanging(string value);
    partial void OnidNHACUNGCAPChanged();
    #endregion
		
		public SANPHAM()
		{
			this._CTHOADONs = new EntitySet<CTHOADON>(new Action<CTHOADON>(this.attach_CTHOADONs), new Action<CTHOADON>(this.detach_CTHOADONs));
			this._CTPHIEUDEXUATs = new EntitySet<CTPHIEUDEXUAT>(new Action<CTPHIEUDEXUAT>(this.attach_CTPHIEUDEXUATs), new Action<CTPHIEUDEXUAT>(this.detach_CTPHIEUDEXUATs));
			this._CTPHIEUNHAPHANGCHINHANHs = new EntitySet<CTPHIEUNHAPHANGCHINHANH>(new Action<CTPHIEUNHAPHANGCHINHANH>(this.attach_CTPHIEUNHAPHANGCHINHANHs), new Action<CTPHIEUNHAPHANGCHINHANH>(this.detach_CTPHIEUNHAPHANGCHINHANHs));
			this._CTPHIEUNHAPHANGTRUSOs = new EntitySet<CTPHIEUNHAPHANGTRUSO>(new Action<CTPHIEUNHAPHANGTRUSO>(this.attach_CTPHIEUNHAPHANGTRUSOs), new Action<CTPHIEUNHAPHANGTRUSO>(this.detach_CTPHIEUNHAPHANGTRUSOs));
			this._KHUYENMAIs = new EntitySet<KHUYENMAI>(new Action<KHUYENMAI>(this.attach_KHUYENMAIs), new Action<KHUYENMAI>(this.detach_KHUYENMAIs));
			this._LICHSUGIAs = new EntitySet<LICHSUGIA>(new Action<LICHSUGIA>(this.attach_LICHSUGIAs), new Action<LICHSUGIA>(this.detach_LICHSUGIAs));
			this._LOAISANPHAM = default(EntityRef<LOAISANPHAM>);
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSANPHAM", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idSANPHAM
		{
			get
			{
				return this._idSANPHAM;
			}
			set
			{
				if ((this._idSANPHAM != value))
				{
					this.OnidSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idSANPHAM = value;
					this.SendPropertyChanged("idSANPHAM");
					this.OnidSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSP", DbType="NVarChar(100)")]
		public string TENSP
		{
			get
			{
				return this._TENSP;
			}
			set
			{
				if ((this._TENSP != value))
				{
					this.OnTENSPChanging(value);
					this.SendPropertyChanging();
					this._TENSP = value;
					this.SendPropertyChanged("TENSP");
					this.OnTENSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(100)")]
		public string HINHANH
		{
			get
			{
				return this._HINHANH;
			}
			set
			{
				if ((this._HINHANH != value))
				{
					this.OnHINHANHChanging(value);
					this.SendPropertyChanging();
					this._HINHANH = value;
					this.SendPropertyChanged("HINHANH");
					this.OnHINHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLOAISANPHAM", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string idLOAISANPHAM
		{
			get
			{
				return this._idLOAISANPHAM;
			}
			set
			{
				if ((this._idLOAISANPHAM != value))
				{
					if (this._LOAISANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLOAISANPHAMChanging(value);
					this.SendPropertyChanging();
					this._idLOAISANPHAM = value;
					this.SendPropertyChanged("idLOAISANPHAM");
					this.OnidLOAISANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNHACUNGCAP", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string idNHACUNGCAP
		{
			get
			{
				return this._idNHACUNGCAP;
			}
			set
			{
				if ((this._idNHACUNGCAP != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidNHACUNGCAPChanging(value);
					this.SendPropertyChanging();
					this._idNHACUNGCAP = value;
					this.SendPropertyChanged("idNHACUNGCAP");
					this.OnidNHACUNGCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTHOADON", Storage="_CTHOADONs", ThisKey="idSANPHAM", OtherKey="idSANPHAM")]
		public EntitySet<CTHOADON> CTHOADONs
		{
			get
			{
				return this._CTHOADONs;
			}
			set
			{
				this._CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTPHIEUDEXUAT", Storage="_CTPHIEUDEXUATs", ThisKey="idSANPHAM", OtherKey="idSANPHAM")]
		public EntitySet<CTPHIEUDEXUAT> CTPHIEUDEXUATs
		{
			get
			{
				return this._CTPHIEUDEXUATs;
			}
			set
			{
				this._CTPHIEUDEXUATs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTPHIEUNHAPHANGCHINHANH", Storage="_CTPHIEUNHAPHANGCHINHANHs", ThisKey="idSANPHAM", OtherKey="idSANPHAM")]
		public EntitySet<CTPHIEUNHAPHANGCHINHANH> CTPHIEUNHAPHANGCHINHANHs
		{
			get
			{
				return this._CTPHIEUNHAPHANGCHINHANHs;
			}
			set
			{
				this._CTPHIEUNHAPHANGCHINHANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CTPHIEUNHAPHANGTRUSO", Storage="_CTPHIEUNHAPHANGTRUSOs", ThisKey="idSANPHAM", OtherKey="idSANPHAM")]
		public EntitySet<CTPHIEUNHAPHANGTRUSO> CTPHIEUNHAPHANGTRUSOs
		{
			get
			{
				return this._CTPHIEUNHAPHANGTRUSOs;
			}
			set
			{
				this._CTPHIEUNHAPHANGTRUSOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_KHUYENMAI", Storage="_KHUYENMAIs", ThisKey="idSANPHAM", OtherKey="idSANPHAM")]
		public EntitySet<KHUYENMAI> KHUYENMAIs
		{
			get
			{
				return this._KHUYENMAIs;
			}
			set
			{
				this._KHUYENMAIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_LICHSUGIA", Storage="_LICHSUGIAs", ThisKey="idSANPHAM", OtherKey="idSANPHAM")]
		public EntitySet<LICHSUGIA> LICHSUGIAs
		{
			get
			{
				return this._LICHSUGIAs;
			}
			set
			{
				this._LICHSUGIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAISANPHAM_SANPHAM", Storage="_LOAISANPHAM", ThisKey="idLOAISANPHAM", OtherKey="idLOAISANPHAM", IsForeignKey=true)]
		public LOAISANPHAM LOAISANPHAM
		{
			get
			{
				return this._LOAISANPHAM.Entity;
			}
			set
			{
				LOAISANPHAM previousValue = this._LOAISANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._LOAISANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAISANPHAM.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._LOAISANPHAM.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._idLOAISANPHAM = value.idLOAISANPHAM;
					}
					else
					{
						this._idLOAISANPHAM = default(string);
					}
					this.SendPropertyChanged("LOAISANPHAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_SANPHAM", Storage="_NHACUNGCAP", ThisKey="idNHACUNGCAP", OtherKey="idNHACUNGCAP", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.SANPHAMs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.SANPHAMs.Add(this);
						this._idNHACUNGCAP = value.idNHACUNGCAP;
					}
					else
					{
						this._idNHACUNGCAP = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_CTPHIEUDEXUATs(CTPHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CTPHIEUDEXUATs(CTPHIEUDEXUAT entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_CTPHIEUNHAPHANGCHINHANHs(CTPHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CTPHIEUNHAPHANGCHINHANHs(CTPHIEUNHAPHANGCHINHANH entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_CTPHIEUNHAPHANGTRUSOs(CTPHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_CTPHIEUNHAPHANGTRUSOs(CTPHIEUNHAPHANGTRUSO entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_KHUYENMAIs(KHUYENMAI entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_KHUYENMAIs(KHUYENMAI entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
		
		private void attach_LICHSUGIAs(LICHSUGIA entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = this;
		}
		
		private void detach_LICHSUGIAs(LICHSUGIA entity)
		{
			this.SendPropertyChanging();
			entity.SANPHAM = null;
		}
	}
}
#pragma warning restore 1591
